create table role (id int8 generated by default as identity, created_by varchar(255), created_date timestamp, is_deleted boolean, last_modified_by varchar(255), last_modified_date timestamp, name varchar(255), primary key (id));
create table ticket (id int8 generated by default as identity, created_by varchar(255), created_date timestamp, is_deleted boolean, last_modified_by varchar(255), last_modified_date timestamp, answer TEXT, description TEXT, ticket_status varchar(255), customer_id int8, primary key (id));
create table user_table (user_type varchar(31) not null, id int8 generated by default as identity, created_by varchar(255), created_date timestamp, is_deleted boolean, last_modified_by varchar(255), last_modified_date timestamp, email varchar(255) not null, first_name varchar(255), is_enable boolean not null, last_name varchar(255), password varchar(255) not null, phone_number varchar(255) not null, role_id int8, primary key (id));

alter table if exists user_table drop constraint if exists define_unique;
alter table if exists user_table add constraint define_unique unique (phone_number, email);
alter table if exists ticket add constraint FKpcf0pr4gciyo5amxijcr8t0iu foreign key (customer_id) references user_table;
alter table if exists user_table add constraint FKrlj7w92dy7h4d255rbat4ovcu foreign key (role_id) references role
